version: '3.3'

services:

  webserver:
    build: ./converter-service/
    image: converter-service
    container_name: converter-service
    ports:
      - "1080:80"
    networks:
      - frontend
    restart: always
    environment:
      - apptoken=${apptoken}
    #volumes:
     # - ../:/var/www/service

networks:
  frontend:
    driver: bridge

